fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    download_file: git://github.com/opentable/puppet-download_file.git
  symlinks:
    nsclient: "#{source_dir}"
