---
.travis.yml:
  secure: "acTGhT7EpADLtW6Ic+pgYo7a7VuF5oe3ll3UrUeXuI2exzj04/SiU2iccHVSypMDRBXVDUPYQY057NT/GVMWnjAfcG1WGmqCPfL8fC5AxIQGgD/GqZmqard+1r0UnPCdkp36POrvs5t5TUgtkcMV4XEm4xxYnMXJxkQS8Z/HVxI="
spec/acceptance/nodesets/archlinux-2-x64.yml:
  unmanaged: true
